# Generated by Django 3.1 on 2020-08-28 15:08

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='product/default.png', max_length=255, null=True, upload_to=product.models.upload_location)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
