# Generated by Django 3.1 on 2020-09-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
