# Generated by Django 3.1 on 2020-08-27 16:00

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product/default.png', max_length=255, null=True, upload_to=product.models.upload_location),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
