# Generated by Django 3.1 on 2020-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200823_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_item',
            name='item_image',
            field=models.ImageField(default='default', upload_to='selling_items'),
        ),
    ]
